### ISSUE TITLE
Please bump @solid/oidc-rp to 0.10.0 in @solid/solid-cli and then bump @solid/solid-cli here 

### ISSUE THREAD

**Issue by CxRes** [jeff-zucker/solid-auth-cli#10]
@solid/oidc-rp 0.9.0 depends on @trust/webcrypto which is deprecated. We need to bump the entire chain of dependencies consequently.

**Comment by jeff-zucker** [comment]
AFAIK, this is done.  Please reopen if I'm missing something

* solid-auth-cli ^0.1.11 requires @solid/cli ^0.1.3
* @solid/cli ^0.1.3 requires @solid/oidc-rp ^0.10.0

**Comment by CxRes** [comment]
Not for now. But I have opened an issue to replace the deprecated @solid/oidc-rp with interop-alliance/oidc-rp in @solid/cli. I'll let you know once that's done and if it needs updating!

**Comment by jeff-zucker** [comment]
Much appreciated, thanks.  Am I correct that a lot of this headache is caused by the 0.x semver numbers?  I bumped all my packages to 1.x even though many are still alpha to avoid this problem.

**Comment by CxRes** [comment]
Unfortunately yes!!!

For now the only other suggestion I can make is that everyone should use dependabot!
