### ISSUE TITLE
Cookie is not attached

### ISSUE THREAD

**Issue by linonetwo** [jeff-zucker/solid-auth-cli#7]
I can PUT with

```js
session.fetch(`${publicFolder}/zhihu/aa.txt`, {
    method: 'PUT',
    headers: { 'Content-Type': 'text', origin: session.webId, cookie: 'nssidp.sid=s%3AtDGDfwwArX4hSoa5L5tVh4YPV9hHjF4D.y%2FSka9fedhN7JGUnrZ8aKN9PzsfZH9gRzCe5fFdWOdw' },
    body: 'asdf',
  });
```

where `cookie` is copy from the browser.

Can you calculate this cookie and attach it automatically?

**Comment by jeff-zucker** [comment]
I have no idea what you are asking or what it would accomplish.  What are
you trying to do?

**Comment by jeff-zucker** [comment]
Why would someone want to attach a browser cookie to a non-browser request?  Why would someone want to make a PUT like that rather than use the normal login and session?  Maybe you should start by describing what the problem is you are trying to solve.

**Comment by linonetwo** [comment]
I wanna PUT a file to localhost POD, and I actually logined

```js
solidAuth.login({
    idp: 'https://localhost:8443/',
    username: config.solidUserName,
    password: config.solidPassword,
  });
```

and fetch using `session.fetch`


But I found in the server-side, its `req.session.userId` always null if there is no cookie, and that make ACL reasoning failed.

**Comment by jeff-zucker** [comment]
This doesn't work?   In which situation doesn't it work?
```javascript
const auth  = require("solid-auth-cli")
const newResource = // some URL on your server

auth.login(
  {
    idp: 'https://localhost:8443/',
    username: config.solidUserName,
    password: config.solidPassword,
  }
).then( ()=>{
    auth.fetch(
       newResource,
       {method:"PUT",body:"some words",headers:{"content-type":"text/plain"}}
    )
})
```

**Comment by linonetwo** [comment]
Wow, that works!

I was using:

```js
const session = await auth.login(
  {
    idp: 'https://localhost:8443',
    username: config.solidUserName,
    password: config.solidPassword,
  }
)
session.fetch(
       newResource,
       {
          method:"PUT",
          body:"some words",
          headers:{"content-type":"text/plain"}
       }
    )
})
```

and that always fails ACL check...

Thank you for this!
